package com.banking.utils;

/**
 * Constants
 * 
 * @author salonegupta
 *
 */
public interface Constants {
	public interface AccountErrors {
		String ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND";
		String TRANSACTION_NOT_FOUND = "TRANSACTION_NOT_FOUND";
	}

	public interface WithdrawalErrors {
		String BELOW_MIN_WITHDRAWAL_AMOUNT = "BELOW_MIN_WITHDRAWAL_AMOUNT";
		String EXCEEDED_MAX_WITHDRAWAL_PER_DAY = "EXCEEDED_MAX_WITHDRAWAL_PER_DAY";
		String EXCEEDED_TOTAL_WITHDRAWALS_PER_DAY = "EXCEEDED_TOTAL_WITHDRAWALS_PER_DAY";
		String EXCEEDED_MAX_WITHDRAWAL_PER_TRANSACTION = "EXCEEDED_MAX_WITHDRAWAL_PER_TRANSACTION";
		String EXCEEDED_ACCOUNT_LIMIT = "EXCEEDED_ACCOUNT_LIMIT";
	}

	public interface DepositErrors {
		String BELOW_MIN_DEPOSIT_AMOUNT = "BELOW_MIN_DEPOSIT_AMOUNT";
		String EXCEEDED_MAX_DEPOSIT_PER_DAY = "EXCEEDED_MAX_DEPOSIT_PER_DAY";
		String EXCEEDED_TOTAL_DEPOSITS_PER_DAY = "EXCEEDED_TOTAL_DEPOSITS_PER_DAY";
		String EXCEEDED_MAX_DEPOSIT_PER_TRANSACTION = "EXCEEDED_MAX_DEPOSIT_PER_TRANSACTION";
	}
}
